defaults:
  - ubtree_hyperparams: default
  - setting: data_size

hydra:
  run:
    dir: ./logs/${setting.experiment}/${hydra.job.override_dirname}
  sweep:
    dir: ./logs/${setting.experiment}/${hydra.job.override_dirname}
    subdir: ./